import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <div className="min-h-screen">
            <Sidebar />

            {/* Main content area: páginas devem remover Sidebar local e usar este wrapper */}
            <div className="ml-64">
              <header className="h-16 border-b bg-white flex items-center px-6">
                <div className="flex-1 text-sm text-muted">&nbsp;</div>
                <div className="flex items-center gap-3">
                  {/* futuro: avatar / nome do usuário */}
                </div>
              </header>

              <main className="pt-6">{children}</main>
            </div>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
